name: build

on:
  workflow_dispatch:
  push:
      branches:
      - main
  pull_request:
    branches:
      - '*'

env:
  DOTNET_NOLOGO: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet 8.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - name: Setup dotnet 9.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x
      - name: Install dependencies
        run: dotnet restore
      - name: Install dotnet-coverage
        run: dotnet tool install -g dotnet-coverage
      - name: Build
        run: dotnet build --configuration Release
      - name: Test with dotnet
        run: dotnet-coverage collect --output $GITHUB_WORKSPACE/report.cobertura.xml --output-format cobertura "dotnet run --no-build --project $GITHUB_WORKSPACE/src/Sidio.Text.Base32.Tests/Sidio.Text.Base32.Tests.csproj"
      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@v5
        with:
          reports: /**/*.cobertura.xml
          targetdir: coveragereport/
          reporttypes: "Cobertura"
      - name: Upload dotnet test results
        uses: coverallsapp/github-action@v2.3.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files: ${{ github.workspace }}/coveragereport/Cobertura.xml
          format: cobertura
        if: ${{ always() }}